name: Docker-AP-VPN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v2
    - name: Build the Docker image
      run: docker build -t docker-ap-vpn .
